library("imager")
Img=load.image("~/Desktop/Work/Digital Image Processing/gitHub/bird.jpg")
Img2=load.image("~/Desktop/Work/Digital Image Processing/gitHub/mario.jpeg")
Img=resize(Img,300,300)
Img2=resize(Img2,300,300)
GrayImg=threshold(grayscale(Img))
GrayImg2=threshold(grayscale(Img2))
plot(GrayImg)
plot(GrayImg2)
plot(GrayImg & GrayImg2)
plot(GrayImg | GrayImg2)
